import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class InvoiceCreate {
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  description: string;
}

export class Invoice {
  @ApiProperty()
  id: number;
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  total_amount: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
