/**
 * This file generated by Apso.
 */
import { InvoiceModule } from './Invoice/Invoice.module';
import { PaymentModule } from './Payment/Payment.module';
import { CustomerModule } from './Customer/Customer.module';
import { VendorModule } from './Vendor/Vendor.module';

export default [InvoiceModule, PaymentModule, CustomerModule, VendorModule];
