import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ActivityCreate {
  @ApiProperty()
  activity_type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  scheduled_date: Date;
  @ApiProperty()
  contact_id: string;
}

export class Activity {
  @ApiProperty()
  id: number;
  @ApiProperty()
  activity_type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  scheduled_date: Date;
  @ApiProperty()
  contact_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
