import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class DealCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  value: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  close_date: string;
  @ApiProperty()
  contact_id: string;
}

export class Deal {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  value: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  close_date: string;
  @ApiProperty()
  contact_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
