import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class NoteCreate {
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  contact_id: string;
}

export class Note {
  @ApiProperty()
  id: number;
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  contact_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
